### ISSUE TITLE
Problem with Benchmark

### ISSUE THREAD

**Issue by MuellerNicolas** [vogloblinsky/web-components-benchmark#59]
Hello,

i'm currently writing my bachelor's thesis about web component libraries. Therefore I wanted to include an up-to-date performance Benchmark with page load and tti. That's why I've tried to use your Repo and just adapt the Version for certain Libraries (Stencil, LitElement).

But I get an error even while installing with the Versions you have set in package.json.

I'm running this setup on a Windows, with Python and VisualStudioCommunity2019 installed.

Steps to reproduce:
> npm i
> cd todomvc && npm i

Then on the next step
> bash install-all.sh

I get the following error but i keeps executing till the end:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@atomico/element/-/element-0.6.7.tgz
npm ERR! 404
npm ERR! 404  '@atomico/element@0.6.7' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

Next problem occurs at the next step:
> npm run build:all

It tell's me that:
```
Der command".." is written wrong or
could not be found.
```

```
Nicolas Müller@DESKTOP-87840TV MINGW64 /c/Nicolas_Studium/Bachelorarbeit/web-components-benchmark/todomvc (master)
$ npm run build:all

> web-components-benchmark-todo@1.0.0 build:all C:\Nicolas_Studium\Bachelorarbeit\web-components-benchmark\todomvc
> run-s build:angular build:atomico build:dojo build:hybrids build:litelement build:native build:hyperHTMLElement build:omi build:riot build:skatejs:lithtml build:skatejs:preact build:slim build:solid build:stencil build:svelte build:vue


> web-components-benchmark-todo@1.0.0 build:angular C:\Nicolas_Studium\Bachelorarbeit\web-components-benchmark\todomvc
> cd angular-elements && npm run build


> angular-elements-todo@0.0.0 prebuild C:\Nicolas_Studium\Bachelorarbeit\web-components-benchmark\todomvc\angular-elements
> rm -rf dist && mkdir dist


> angular-elements-todo@0.0.0 build C:\Nicolas_Studium\Bachelorarbeit\web-components-benchmark\todomvc\angular-elements
> ../../node_modules/.bin/run-s minify-html build-js minify-js

Der Befehl ".." ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-elements-todo@0.0.0 build: `../../node_modules/.bin/run-s minify-html build-js minify-js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-elements-todo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicolas Müller\AppData\Roaming\npm-cache\_logs\2021-04-01T13_57_25_167Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-components-benchmark-todo@1.0.0 build:angular: `cd angular-elements && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-components-benchmark-todo@1.0.0 build:angular script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicolas Müller\AppData\Roaming\npm-cache\_logs\2021-04-01T13_57_25_186Z-debug.log
ERROR: "build:angular" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! web-components-benchmark-todo@1.0.0 build:all: `run-s build:angular build:atomico build:dojo build:hybrids build:litelement build:native build:hyperHTMLElement build:omi build:riot build:skatejs:lithtml build:skatejs:preact build:slim build:solid build:stencil build:svelte build:vue`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the web-components-benchmark-todo@1.0.0 build:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nicolas Müller\AppData\Roaming\npm-cache\_logs\2021-04-01T13_57_25_228Z-debug.log

```

Can anyone please help me with this?

Maybe to fix the first issue: How could I exclude certain Technologies like Atomico from the benchmark?

Thank you very much for your support

**Comment by MuellerNicolas** [comment]
Update:

- I've installed it on a Ubuntu VM and the second error didn't occure anymore (Atomico error continous)

Now if have the following problem:
After the steps:
> npm i
> cd todomvc && npm i
> bash install-all.sh
> npm run build:all
> cd pascal-triangle && npm i
> bash install-all.sh
> npm run build:all
> npm run serve #on root

I open a browser (Chromium and Firefox testet)
For the address `http://localhost:3000/`
it says `Cannot GET /`

What I have tried: set `network.http.spdy.enabled.http2` to `false` which had no affect.

Can anyone help me please with this issue?^

**EDIT - Got it working**
Okay - my fault - i misinterpredet the readme - it was meant to execute run serve and run benchmark in 2 different shells

**Comment by MuellerNicolas** [comment]
Now after running `npm run serve` on root and in a seperate tab in todomvc-directory `npm run run:benchmark`:
I get the following output: (if excluded some libraries from meta.js)

```
nicolas@nicolasVM:~/web-components-benchmark/todomvc$ npm run run:benchmark

> web-components-benchmark-todo@1.0.0 run:benchmark /home/nicolas/web-components-benchmark/todomvc
> npm run benchmark


> web-components-benchmark-todo@1.0.0 benchmark /home/nicolas/web-components-benchmark/todomvc
> node benchmarks/benchmark.js

**********************
* TODO MVC BENCHMARK *
**********************
********************
* LitElement
********************

Average time for Page Load : 0 ms


Average time for time to interactive : NaN ms

(node:16653) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'shadowRoot' of null
    at __puppeteer_evaluation_script__:1:34
    at ExecutionContext.evaluateHandle (/home/nicolas/web-components-benchmark/node_modules/puppeteer/lib/ExecutionContext.js:80:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/nicolas/web-components-benchmark/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.evaluateHandle (/home/nicolas/web-components-benchmark/node_modules/puppeteer/lib/Page.js:310:20)
  -- ASYNC --
    at Page.<anonymous> (/home/nicolas/web-components-benchmark/node_modules/puppeteer/lib/helper.js:110:27)
    at benchCreate (/home/nicolas/web-components-benchmark/common/helpers.js:115:40)
(node:16653) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16653) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

What am I doin wrong? :(

**Comment by vogloblinsky** [comment]
Hi @MuellerNicolas 
It seems some libraries need an update.
I watch that as soon as possible.

**Comment by vogloblinsky** [comment]
hi @MuellerNicolas 
look that link https://webcomponents.dev/blog/all-the-ways-to-make-a-web-component/
i think you will find useful informations
